package domain.user.model

data class TrackingSecurity(
    val id: Long,
    val ticker: String,
    val name: String,
    val uid: String,
    val targetPrice: Double?,
    val lowTargetPrice: Double?,
    val targetDeviation: Double,
    val isActive: Boolean,
    val remainActive: Boolean,
    val note: String?,
    val noteUpdatedMs: Long?,
    val showNote: Boolean,
    val shouldNotify: Boolean,
    val shouldNotifyRsi: Boolean,
    val shouldNotifyBb: Boolean,
    val shouldNotifySrsi: Boolean,
    val type: SecurityType,
    val lastUnboundUpdateSec: Long,
    val lastUnboundUpdatePrice: Double?,
) {

    companion object {
        fun default(
            ticker: String,
            name: String,
            uid: String,
            type: SecurityType,
            id: Long = 0L,
            targetPrice: Double? = null,
            lowTargetPrice: Double? = null,
            targetDeviation: Double = 0.1,
            isActive: Boolean = true,
            remainActive: Boolean = true,
            note: String? = null,
            noteUpdatedMs: Long? = null,
            showNote: Boolean = true,
            shouldNotify: Boolean = true,
            shouldNotifyRsi: Boolean = true,
            shouldNotifyBb: Boolean = true,
            shouldNotifySrsi: Boolean = true,
            lastUnboundUpdateSec: Long = 0,
            lastUnboundUpdatePrice: Double? = null,
        ) = TrackingSecurity(
            id = id,
            ticker = ticker,
            name = name,
            uid = uid,
            targetPrice = targetPrice,
            lowTargetPrice = lowTargetPrice,
            targetDeviation = targetDeviation,
            isActive = isActive,
            remainActive = remainActive,
            note = note,
            noteUpdatedMs = noteUpdatedMs,
            showNote = showNote,
            shouldNotify = shouldNotify,
            shouldNotifyRsi = shouldNotifyRsi,
            shouldNotifyBb = shouldNotifyBb,
            shouldNotifySrsi = shouldNotifySrsi,
            type = type,
            lastUnboundUpdateSec = lastUnboundUpdateSec,
            lastUnboundUpdatePrice = lastUnboundUpdatePrice
        )
    }
}